## Configuration for mysql database


spring.application.name=TodoRails
logging.level.org.springframework.web=DEBUG

# MySQL database configurations
spring.datasource.url=jdbc:mysql://localhost:3306/todorails?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password={Type-your_mysql-db_password here}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Mapping errors
server.error.path=/error





## Configuration for H2database


#spring.application.name=TodoRails
#logging.level.org.springframework.web=DEBUG
#
##H2 database
#spring.datasource.url=jdbc:h2:mem:todorails
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver
#
## JPA and Hibernate configurations
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## Mapping errors
#server.error.path=/error









